# -*- coding: utf-8 -*-
"""assignment orperator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qQpwT_oJ6xAj34iMHYCmAZc8TJVYyqEy
"""

name = 'Aditi Panchal'

name

# convert it into caps lock
# ADITI PANCHAL

name.upper ()

name

name.lower()

name1 ="ADIti paNChal"

# capital letter should become small and vice versa

name1

name1. swapcase()

# 1.remove left space
#  2.remove right space
# remove both right and left space

name2 = "    sanika      kshirsagar     "

name2 .lstrip()

name2.strip()

name3 = "Prathamesh Macharla"

# bring this output
# **** Prathamesh  macharla ****

name3 .center(50,'*')

name4 = "shreya nagame"

name4.islower()

name4

name4

name5 = 'SHREYA'

name5.isupper()

name5.isspace()

name4

name5.islower()

